ETAB
237	01.07.1992	PROD	HLIQ  HWEF    BHPT 10 
--********************--
322	01.06.1997	PROD	HLIQ  HWEF    BHPT 10 
--********************--
321	01.06.1998	PROD	HLIQ  HWEF    BHPT 10 
--********************--
326	01.02.1997	PROD	HLIQ  HWEF    BHPT 10 
--********************--
368	01.01.2009	PROD	HLIQ  HWEF    BHPT 10 
--********************--
325	01.05.2003	INJE	HWAT  HWEF    BHPT 500 
--********************--
328	01.03.1999	PROD	HLIQ  HWEF    BHPT 10 
--********************--
144	01.12.1993	PROD	HLIQ  HWEF    BHPT 10 
--********************--
ENDE